
server:
  port: 8080

spring:
  datasource:
    username: root
    password: bwk123
    url: jdbc:mysql://localhost:3306/ssmbuild?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss   # 时间日期格式化
    pathmatch:
      matching-strategy: ant_path_matcher

# 整合mybatis
mybatis:
  type-aliases-package: cn.bianwenkai.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
