
server:
  port: 8080

spring:
  datasource:
    username: root
    password: bwk123
    url: jdbc:mysql://localhost:3306/dust_monitor?useUnicode=true&characterEncoding=utf-8&useSSL=true&&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8



  mail:
    username: 1467295546@qq.com
    password: wrovfihvrvmajaia
    host: smtp.qq.com
    properties: mail.smtp.ssl.enable=true
    port: 465
  redis:
    host: 127.0.0.1
    port: 6379

# 整合mybatis
mybatis:
  type-aliases-package: cn.bianwenkai.entity , cn.bianwenkai.vo
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
